### ISSUE TITLE
Thank you for your excellent work!, When will the whole code and data be released?

### ISSUE THREAD

**Issue by LinZhuoChen** [JokerYan/NeRF-DS#1]
Looking forward to your reply~

**Comment by JokerYan** [comment]
Thank you for being interested in our work. You can already access the data from the GitHub release. Please let me know if you have any problem downloading it.

As for the code, it is actually already pushed to this repo, but I am now busy with the NeuIPS deadline. I will update the instructions for running the code around two weeks later.

**Comment by LinZhuoChen** [comment]
Thank you for your kindly reply~
