### ISSUE TITLE
SyntaxError: Unable to parse value. (line 1)

### ISSUE THREAD

**Issue by rishavbb** [JokerYan/NeRF-DS#2]
Firstly, thanks for the amazing work. I am facing this issue from train.py 

```
gin.parse_config_files_and_bindings(
      config_files=gin_configs,
      bindings=FLAGS.gin_bindings,
      skip_unknown=True)
```

```
Exception has occurred: SyntaxError
Unable to parse value. (line 1)
  File "/home/rishav/NeRF-DS/train.py", line 155, in main
    gin.parse_config_files_and_bindings(
  File "/home/rishav/NeRF-DS/train.py", line 470, in <module>
    app.run(main)
SyntaxError: Unable to parse value. (line 1)
```

**Comment by JokerYan** [comment]
Hi, thank you for being interested in our work. Unfortunately I am currently on vacation and cannot really reproduce this problem on my workstation.

I suspect this is related to the line break used for different operating system. May I ask on which operating system are you running the code?

**Comment by rishavbb** [comment]
Ubuntu 22.04.2

**Comment by JokerYan** [comment]
Then it shouldn't be the os. Can you kindly attach the command you use to run it, so that I can try to debug a bit? Thank you!

**Comment by rishavbb** [comment]
I found the error. I was trying to replicate `--gin_bindings="data_dir='$DATASET_PATH'"` mentioned in HyperNeRF, whereas it should have been `--gin_bindings data_dir=\'$DATA_DIR' `

Sorry for this and thanks for the quick response.
