### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by mra-h** [JokerYan/NeRF-DS#3]
Hello,

Thanks for the amazing work!

I am not familiar with jax and I am wondering how do you debug the training? For example, is there any flag that allows me to inspect the value of the tensors inside the [`ptrain_step`](https://github.com/JokerYan/NeRF-DS/blob/f0bd3844f47a5c77289527a404a954e459a4e116/train.py#L430) function?

Thanks!

**Comment by JokerYan** [comment]
Debugging jax is very painful. I don't remember finding any good printing function when I was writing this repo, but it seems that there is a new `jax.debug.print` you can try.
