### ISSUE TITLE
Wrong gradient for normals?

### ISSUE THREAD

**Issue by mra-h** [JokerYan/NeRF-DS#4]
Hi,

In the paper the predicted normal is supervised with the gradient of the sigma MLP wrt the warped point `x'`
![image](https://github.com/JokerYan/NeRF-DS/assets/131394031/bab3a34a-3998-4d60-85f6-15e3fd09162d)

However, in the code, the gradient is computed [wrt the input point `x`](https://github.com/JokerYan/NeRF-DS/blob/f0bd3844f47a5c77289527a404a954e459a4e116/hypernerf/models.py#L1069), instead of the warped point `x'`. Is this the correct behaviour?

**Comment by JokerYan** [comment]
Thank you for your question.
The gradient used to supervise the norm prediction is controlled using `model.norm_supervision_type`.
When its value is 'direct', the gradient wrt `x` is used. 
When its value is 'canonical', the gradient wrt `x'` is used.
